# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rockpool < Formula
  desc "Simple tool to set up a Lagoon instance locally"
  homepage "https://github.com/salsadigitalauorg/rockpool"
  version "0.4.8"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/salsadigitalauorg/rockpool/releases/download/v0.4.8/rockpool-Linux-x86_64.tar.gz"
      sha256 "5220923cc16c4aaff8ddd988fc6a503d40320d102df3adc46fed6dd019778db7"

      def install
        bin.install "rockpool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/salsadigitalauorg/rockpool/releases/download/v0.4.8/rockpool-Linux-aarch64.tar.gz"
      sha256 "e96e72a6bd7ffb5f824395ea6052086c00a7c932bc7c9307658cb2c076ddfe52"

      def install
        bin.install "rockpool"
      end
    end
  end

  test do
    system "#{bin}/rockpool version"
  end
end
